version: '3.8'

services:
  pembayaran-pasien:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pembayaran_pasien
    ports:
      - "8084:80"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=pembayaran
      - DB_NAME=hospital_billing
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pembayaran
      MYSQL_DATABASE: hospital_billing
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
